### ISSUE TITLE
Error in examples/Cam001.kt, "Selected framerate (29.970030) is not supported by the device"

### ISSUE THREAD

**Issue by goudreinette** [openrndr/workshop-tumo#1]
Hey there, 

Awesome work with the examples and Olive,
I noticed a small thingy on my MacBook Pro 13' 2016:

When I try to launch Examples/Cam001.kt, I get the following error:

```
[avfoundation @ 0x7fed672af800] Selected framerate (29.970030) is not supported by the device
[avfoundation @ 0x7fed672af800] Supported modes:
[avfoundation @ 0x7fed672af800]   1280x720@[1.000000 30.000000]fps
[avfoundation @ 0x7fed672af800]   1280x720@[1.000000 30.000000]fps
[avfoundation @ 0x7fed672af800]   1280x720@[1.000000 30.000000]fps
[avfoundation @ 0x7fed67ac3a00] Selected framerate (29.970030) is not supported by the device
[avfoundation @ 0x7fed67ac3a00] Supported modes:
[avfoundation @ 0x7fed67ac3a00]   1280x720@[1.000000 30.000000]fps
[avfoundation @ 0x7fed67ac3a00]   1280x720@[1.000000 30.000000]fps
[avfoundation @ 0x7fed67ac3a00]   1280x720@[1.000000 30.000000]fps
Exception in thread "main" org.openrndr.ffmpeg.adopted.FrameGrabber$Exception: avformat_open_input() error -5: Could not open input "0". (Has setFormat() been called?)
	at org.openrndr.ffmpeg.adopted.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:638)
	at org.openrndr.ffmpeg.adopted.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:567)
	at org.openrndr.ffmpeg.FFMPEGVideoPlayer.start(FFMPEGVideoPlayer.kt:102)
	at examples.Cam001Kt$main$1$2.invoke(Cam001.kt:24)
	at examples.Cam001Kt$main$1$2.invoke(Cam001.kt)
	at org.openrndr.ApplicationBuilder$program$1.setup(ApplicationBuilder.kt:14)
	at org.openrndr.internal.gl3.ApplicationGLFWGL3.loop(ApplicationGLFWGL3.kt:511)
	at org.openrndr.Application$Companion.run(Application.kt:29)
	at org.openrndr.ApplicationKt.application(Application.kt:71)
	at org.openrndr.ApplicationBuilderKt.application(ApplicationBuilder.kt:34)
	at examples.Cam001Kt.main(Cam001.kt:15)
	at examples.Cam001Kt.main(Cam001.kt)
```

Is this default framerate correct? 
Initializing FFMPEGVideoPlayer with 30 fps fixes the problem for me:

```
val camera = FFMPEGVideoPlayer.fromDevice(FFMPEGVideoPlayer.defaultDevice(), 1280, 720, 30.0)
camera.start()
```

**Comment by edwinRNDR** [comment]
Hi @reinvdwoerd. Thanks for reporting this. It is a known issue in either OPENRNDR or ffmpeg itself in which opening the webcam at the default framerate fails. Indeed the work-around is to specify the framerate manually.

**Comment by goudreinette** [comment]
Thanks for the notice!
